### PR TITLE
Feature/story test/procedural test cases

### PR DESCRIPTION
**Pull request by dumebi**
Run `yarn test mainnet` to recreate testing

This PR creates a new procedural structure which creates a permutation of actions on each domain in a 
```
storyDomain  {
  domainName: 'DAPP.LEND.AAVE',
  scenarios: [
    { domain: 'DAPP', actions: [Array] },
    { domain: 'DAPP', actions: [Array] }
  ]
}
```

- created new procedural test structure using permutation of actions in a story domain
- reimplemented test drivers to match these structure

### CODE REVIEW

**Comment by mkhoury93** [comment]
@dumebi, can you write a description here of what i'm expected to test when switching branches?

**Comment by dumebi** [comment]
> hey @dumebi, can you write a description here of what we're expected to test when we switch to your `feature/story_test` branch?

just did @mkhoury93

**Comment by mkhoury93** [comment]
`yarn test mainnet` doesn't work right away since new packages have been added. `yarn install` has to be executed prior

**Review by mkhoury93 — COMMENTED** [review]
tests are successfully being generated by pushing actions on what each story requires

**Pull request merged**
